export enum PagesEnums {
  /*************MODULES***************/
  STORES=1,
  ROLES=2,
  ACCOUNTS = 3,
  HR=4,
  /*************USER_ROLES***************/
  /****************** module:1 STORES المخازن ************************/
  WITHDRAW = 1,
  STRAdd = 2,
  STR_OPENING_STOCK = 3,
  EMPLOYEE_OPENING = 4,
  EMPLOYEE_OPENING_CUSTODY = 5,
  COMMODITY = 6,
  GRADE = 7,
  STR_PLATOON = 8,
  GROUP1 = 9,
  UNIT = 10,
  ITEMES1 = 11,
  PRODUCTS = 12,
  STORE = 13,
  COST_CENTER = 14,
  STR_VENDOR = 15,
  MODEL = 16,
  STORES_ACCOUNTS = 17,
  PRODUCT_SERIAL=18,
 STRUSERSTORE =19,
 StrStockTaking=20,
 /****************** module:2 Roles الصلاحيات************************/
  PR_USER = 21,
  PR_GROUP = 22,
   /****************** module:3 ACCOUNTS الحسابات************************/
  ADD_ACCOUNT=23,
  AccountHierarchy=24,
  FiAccountItem=25,
  AccountParent=26,
  FIJournal=27,
  EntrySource =28,
  EntrySourceType=29,
  FI_ENTRY=30,
   /****************** module:4 HR شئون العاملين************************/
HR_JOB_TITLE=31,
HR_INCENTIVE=32,
HR_HIRING_TYPE=33,
SeveranceReason =34,
HR_MILLIIRY_STATE=35,
CITY=36,
CITY_STATE=37,
QUALIFICATION=38,
QUALIATIVE_GROUP =39,
WorkPlace=40,
specialization=41,
HR_POSTION=42,
hr_Disciplinary=43,
HR_VACATION =44,
HR_employeeVacationBalance=45,
HR_Employee_VACATION=46,
HR_Employee_Disciplinary=47,
HR_financialDegree=48,
HR_employeeFinancialDegree =49,
HR_employee_position=50,
HR_employeeAppraisal =51,
HR_employee=52,
Employee_qualifications=53,
Qualification_level=54,

}
